# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package and Deploy to AWS

on:
  push:
    branches: [ main , workflow_dispatch ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

#    - uses: actions/checkout@v2

    - name: Create ZIP deployment package
      run: zip -r deploy_package.zip ./

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"

    - name: Upload package to S3 bucket
      run: aws s3 cp deploy_package.zip s3://vacation-planner-v2-be-cd-github/

    - name: Create new ElasticBeanstalk Application Version
      run: |
        aws elasticbeanstalk create-application-version \
        --application-name vacation-planner-v2-be \
        --source-bundle S3Bucket="vacation-planner-v2-be-cd-github",S3Key="deploy_package.zip" \
        --version-label "ver-${{ github.sha }}" \
        --description "commit-sha-${{ github.sha }}"

    - name: Deploy new ElasticBeanstalk Application Version
      run: aws elasticbeanstalk update-environment --environment-name VacationPlannerV2-BE-dev3 --version-label "ver-${{ github.sha }}"

